apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-devops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-devops
  template:
    metadata:
      labels:
        app: php-devops
    spec:
      containers:
      - name: php-devops-container
        image: 180935779261.dkr.ecr.us-east-1.amazonaws.com/php-devops-app:latest
        ports:
        - containerPort: 80
---

# This will create
# 2 Kubernetes Pods
# running your PHP container